name: CI
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    lint:
        name: Lint & Format Check
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                node-version: '20'
            
            - name: Install Dependencies
              run: npm ci

            - name: Run Lint
              run: npx eslint . --ext .ts,.tsx
            
            - name: Run Format Check
              run: npx prettier --check .
            
            - name: Run TypeScript Compiler
              run: npx tsc --noEmit

            # Waiting for the test suite to be ready
            #- name: Run Tests
            # run: npx vitest run --reporter=default
        

            
